### ISSUE TITLE
Make public

### ISSUE THREAD

**Issue by rizken** [bjornet/jirabranchcreator#21]
# Epic Story
As a developer, I want to be able to install ttb as a npm package, so that I can use ttb in a consistent way

## Acceptance Criteria
- [ ] it should have a readme that is true and helpful
- [ ] it should rename the repository to "ttb"
- [ ] it should not have legacy code in the repo

## User Stories
- #23 
- #22 
- #24 
- #25
